# Generated by Django 2.1.7 on 2019-02-27 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineID', models.PositiveIntegerField()),
                ('DateStamp', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('TimeStamp', models.TimeField(default='20:00')),
                ('Details', models.CharField(max_length=500)),
                ('Comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
