# Generated by Django 2.1.7 on 2019-03-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceLog', '0003_remove_maintenancelog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='Name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
