# Generated by Django 2.1.7 on 2019-03-02 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceLog', '0004_maintenancelog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=500)),
                ('MachineID', models.PositiveIntegerField()),
                ('DateStamp', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('TimeStamp', models.TimeField(default='20:00')),
                ('Details', models.CharField(max_length=500)),
                ('Comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
