# Generated by Django 2.1.7 on 2019-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceLog', '0005_pendinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinglog',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
