# Generated by Django 2.1.7 on 2019-03-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceLog', '0006_pendinglog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingLog',
        ),
    ]
