# Generated by Django 2.1.7 on 2019-02-27 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='Date',
        ),
        migrations.AddField(
            model_name='workorder',
            name='DateStamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
