# Generated by Django 2.1.7 on 2019-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0002_auto_20190227_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='DateStamp',
            field=models.DateField(default='2011-10-01'),
        ),
    ]
