# Generated by Django 2.1.7 on 2019-02-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_asset_maintenancelog_spares_usagelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='MachineId',
            new_name='MachineID',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='ProdlineNum',
            new_name='Prodline',
        ),
    ]
