# Generated by Django 2.1.7 on 2019-02-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0004_auto_20190227_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancelog',
            name='MachineId',
        ),
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
    ]
