# Generated by Django 2.1.7 on 2019-02-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_auto_20190227_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMC',
        ),
        migrations.RemoveField(
            model_name='spares',
            name='MachineId',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='MachineId',
        ),
        migrations.DeleteModel(
            name='Spares',
        ),
        migrations.DeleteModel(
            name='UsageLog',
        ),
    ]
