# Generated by Django 2.1.7 on 2019-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineId', models.PositiveIntegerField()),
                ('ComponentName', models.CharField(max_length=250)),
                ('Count', models.PositiveIntegerField()),
            ],
        ),
    ]
