# Generated by Django 2.1.7 on 2019-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0002_auto_20190227_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineID', models.PositiveIntegerField(default=0)),
                ('ComponentName', models.CharField(max_length=250)),
                ('Count', models.PositiveIntegerField()),
                ('CostOfPart', models.FloatField(default=0.0)),
                ('NumberOfParts', models.PositiveIntegerField(default=0)),
                ('TotalAmount', models.FloatField(default=0.0)),
            ],
        ),
    ]
