# Generated by Django 2.1.7 on 2019-03-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='NumberOfParts',
        ),
    ]
