# Generated by Django 2.1.7 on 2019-03-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0004_remove_orders_numberofparts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
