# Generated by Django 2.1.7 on 2019-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0005_auto_20190302_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Customer',
            field=models.CharField(default='', max_length=250),
        ),
    ]
