# Generated by Django 2.1.7 on 2019-03-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0006_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default='09-09-2018 20:00'),
        ),
    ]
