# Generated by Django 2.1.7 on 2019-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0007_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default='2019-03-02 20:00'),
        ),
    ]
