# Generated by Django 2.1.7 on 2019-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0009_auto_20190303_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
    ]
