# Generated by Django 2.1.7 on 2019-03-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0013_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
    ]
