# Generated by Django 2.1.7 on 2019-03-02 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0014_remove_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Date2',
            field=models.DateTimeField(default=datetime.date(2019, 3, 3)),
        ),
    ]
