# Generated by Django 2.1.7 on 2019-03-02 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparesUpKeep', '0015_order_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date2',
            field=models.DateField(default=datetime.date(2019, 3, 3)),
        ),
    ]
