# Generated by Django 2.1.7 on 2019-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCRenewal', '0002_auto_20190227_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='ExpiryDate',
            field=models.DateField(default='2011-10-01'),
        ),
    ]
