# Generated by Django 2.1.7 on 2019-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCRenewal', '0003_auto_20190228_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='AMCCompany',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='Category',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='Company',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
