# Generated by Django 2.1.7 on 2019-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCRenewal', '0004_auto_20190302_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc',
            old_name='ExpiryDate',
            new_name='LastRenewal',
        ),
        migrations.AddField(
            model_name='amc',
            name='Frequency',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
