# Generated by Django 2.1.7 on 2019-03-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCRenewal', '0005_auto_20190302_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc',
            old_name='AMCCompany',
            new_name='Facility',
        ),
        migrations.RenameField(
            model_name='amc',
            old_name='Company',
            new_name='Supplier',
        ),
        migrations.AddField(
            model_name='amc',
            name='Details',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
